#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# Binary space partitioning, stack, or float
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Gap
# yabai -m config top_padding 10
# yabai -m config bottom_padding 10
# yabai -m config left_padding 10
# yabai -m config right_padding 10
# yabai -m config window_gap 10

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow on \
	window_animation_duration 0.0 \
	window_animation_frame_rate 120 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity on \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 10 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 10 \
	layout bsp \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# Sketchybar support
# yabai -m config external_bar main:30:0
# yabai -m config external_bar               all:35:0

# Window borders -- Removed: https://github.com/koekeishiya/yabai/issues/1889

# Split ratio
# yabai -m config auto_balance off
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

# Mouse
# yabai -m config mouse_follows_focus off
# yabai -m config mouse_modifier alt
# right click + drag
# yabai -m config mouse_action2 resize

# No tiling
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Venus$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^DesktopServicesHelper$" manage=off
yabai -m rule --add app="^QuickLookUIService" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" manage=off
yabai -m rule --add label="Music" app="^Music$" manage=off
yabai -m rule --add label="QQ Music" app="^QQ音乐$" manage=off
yabai -m rule --add label="QQ" app="^QQ$" manage=off
yabai -m rule --add label="Docker" app="^Docker$" manage=off
yabai -m rule --add label="Docker" app="^Docker Desktop$" manage=off
yabai -m rule --add label="Element" app="^Element$" manage=off
yabai -m rule --add label="Chrome" app="^Google Chrome$" title="^DevTools" manage=off
yabai -m rule --add label="JetBrains Toolbox" app="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="^(Safari|SandboxBroker|eteams|Web App)$" manage=off
yabai -m rule --add app="^Obsidian$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^FileZilla$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^The Unarchiver$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^PlayCover$" manage=off
yabai -m rule --add app="^START$" manage=off

echo "yabai configuration loaded.."
