#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# Binary space partitioning, stack, or float
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Gap
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10
# Sketchybar support
# yabai -m config external_bar main:30:0
# yabai -m config external_bar               all:35:0     \
#                 mouse_follows_focus        off          \
#                 focus_follows_mouse        off          \
#                 window_zoom_persist        off          \
#                 window_placement           second_child \
#                 window_topmost             off          \
#                 window_shadow              float        \
#                 window_opacity             on           \
#                 window_opacity_duration    0.2          \
#                 active_window_opacity      1.0          \
#                 normal_window_opacity      0.95         \
#                 window_animation_duration  0.3          \
#                 insert_feedback_color      0xff9dd274   \
#                 split_ratio                0.50         \
#                 auto_balance               off          \
#                 auto_padding               on           \
#                 mouse_modifier             fn           \
#                 mouse_action1              move         \
#                 mouse_action2              resize       \
#                 mouse_drop_action          swap         \
#                 top_padding                14           \
#                 bottom_padding             8            \
#                 left_padding               8            \
#                 right_padding              8            \
#                 window_gap                 10

# Window borders -- Removed: https://github.com/koekeishiya/yabai/issues/1889
# yabai -m config window_border on
# yabai -m config window_border_width 2
# yabai -m config window_border_blur on
# yabai -m config active_window_border_color 0xff7aa2f7 # Tokyonight blue
# yabai -m config normal_window_border_color 0xfff7768e # Tokyonight red

# Split ratio
yabai -m config auto_balance off

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# Mouse
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier alt
# right click + drag
yabai -m config mouse_action2 resize

# No tiling
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Venus$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^DesktopServicesHelper$" manage=off
yabai -m rule --add app="^QuickLookUIService" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Mail" app="^Mail$" manage=off
